apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-and-push-dockerfile
  namespace: cluster-registry
spec:
  entrypoint: build-all
  volumes:
  - name: redis-dockerfile
    configMap:
      name: redis-dockerfile
  - name: sentinel-dockerfile
    configMap:
      name: sentinel-dockerfile
  templates:
  - name: build-all
    steps:
    - - name: build-redis
        template: build-redis-image
      - name: build-sentinel
        template: build-sentinel-image
  
  - name: build-redis-image
    container:
      image: moby/buildkit:latest
      command:
      - buildctl-daemonless.sh
      args:
      - build
      - --frontend=dockerfile.v0
      - --local=context=/workspace
      - --local=dockerfile=/workspace
      - --output=type=image,name=docker-registry.cluster-registry.svc.cluster.local:5000/custom-redis:latest,push=true,registry.insecure=true
      volumeMounts:
      - name: redis-dockerfile
        mountPath: /workspace
        readOnly: true
      securityContext:
        privileged: true
