apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: cluster-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: cluster-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
        env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin
          value: '["*"]'
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods
          value: '["HEAD", "GET", "OPTIONS", "DELETE"]'
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers
          value: '["Authorization", "Accept", "Content-Type"]'
      volumes:
      - name: registry-storage
        persistentVolumeClaim:
          claimName: registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: cluster-registry
spec:
  selector:
    app: docker-registry
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-external
  namespace: cluster-registry
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: cluster-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
      - name: ui
        image: joxit/docker-registry-ui:latest
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: REGISTRY_TITLE
          value: Kubelocal Docker Registry
        - name: DELETE_IMAGES
          value: "false"
        - name: SHOW_CONTENT_DIGEST
          value: "true"
        - name: NGINX_PROXY_PASS_URL
          value: http://docker-registry:5000
        - name: SINGLE_REGISTRY
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: cluster-registry
spec:
  selector:
    app: registry-ui
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-registry
  namespace: cluster-registry
  annotations:
    cert-manager.io/cluster-issuer: ishiori-local-general-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - registry.kube.ishiori.lnet
    secretName: registry-tls
  rules:
  - host: registry.kube.ishiori.lnet
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: registry-ui
            port:
              number: 80
