apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: reset-registry
  namespace: cluster-registry
spec:
  entrypoint: reset
  templates:
  - name: reset
    steps:
    - - name: list-repos
        template: list-repositories
    - - name: delete-repos
        template: delete-repository
        arguments:
          parameters:
          - name: repo
            value: "{{item}}"
        withParam: "{{steps.list-repos.outputs.result}}"
    - - name: garbage-collect
        template: garbage-collection

  - name: list-repositories
    script:
      image: curlimages/curl:latest
      command: [sh]
      source: |
        #!/bin/sh
        curl -s http://docker-registry.cluster-registry.svc.cluster.local:5000/v2/_catalog | \
        grep -o '"repositories":\[[^]]*\]' | \
        grep -o '\[[^]]*\]' | \
        sed 's/\[//;s/\]//;s/"//g' | \
        tr ',' '\n' | \
        sed 's/^/"/;s/$/"/' | \
        paste -sd ',' | \
        sed 's/^/[/;s/$/]/'

  - name: delete-repository
    inputs:
      parameters:
      - name: repo
    script:
      image: curlimages/curl:latest
      command: [sh]
      source: |
        #!/bin/sh
        set -x
        REPO="{{inputs.parameters.repo}}"
        echo "Processing repository: $REPO"

        # Get all tags for the repository
        TAGS_JSON=$(curl -s http://docker-registry.cluster-registry.svc.cluster.local:5000/v2/${REPO}/tags/list)
        echo "Tags JSON: $TAGS_JSON"

        TAGS=$(echo "$TAGS_JSON" | grep -o '"tags":\[[^]]*\]' | grep -o '\[[^]]*\]' | sed 's/\[//;s/\]//;s/"//g' | tr ',' ' ')
        echo "Tags found: $TAGS"

        # Delete each tag
        for TAG in $TAGS; do
          echo "Processing tag: $TAG"

          # Get digest - try different manifest types
          DIGEST=$(curl -s -I -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            http://docker-registry.cluster-registry.svc.cluster.local:5000/v2/${REPO}/manifests/${TAG} | \
            grep -i docker-content-digest | awk '{print $2}' | tr -d '\r\n ')

          if [ -z "$DIGEST" ]; then
            echo "Trying OCI manifest format..."
            DIGEST=$(curl -s -I -H "Accept: application/vnd.oci.image.manifest.v1+json" \
              http://docker-registry.cluster-registry.svc.cluster.local:5000/v2/${REPO}/manifests/${TAG} | \
              grep -i docker-content-digest | awk '{print $2}' | tr -d '\r\n ')
          fi

          if [ -n "$DIGEST" ]; then
            echo "Deleting ${REPO}:${TAG} with digest: ${DIGEST}"
            RESULT=$(curl -v -X DELETE http://docker-registry.cluster-registry.svc.cluster.local:5000/v2/${REPO}/manifests/${DIGEST} 2>&1)
            echo "Delete result: $RESULT"
          else
            echo "No digest found for ${REPO}:${TAG}"
          fi
        done
        echo "Finished processing $REPO"

  - name: garbage-collection
    script:
      image: registry:2
      command: [sh]
      source: |
        #!/bin/sh
        set -x
        echo "Running garbage collection on registry..."
        registry garbage-collect /etc/docker/registry/config.yml
        echo "Garbage collection completed"
      volumeMounts:
      - name: registry-storage
        mountPath: /var/lib/registry
    volumes:
    - name: registry-storage
      persistentVolumeClaim:
        claimName: registry-pvc
