---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /version {
            default_type text/plain;
            return 200 "nginx/$nginx_version\n";
        }
        
        location /hostname {
            default_type text/plain;
            return 200 "$hostname\n";
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-version-page
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Nginx Version</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 50px; }
            .version { font-size: 24px; color: #009639; }
        </style>
    </head>
    <body>
        <h1>Nginx Server</h1>
        <p class="version">Version: <span id="version">Loading...</span></p>
        <p>Pod: <span id="hostname">Loading...</span></p>
        <script>
            fetch('/version')
              .then(r => r.text())
              .then(v => document.getElementById('version').textContent = v.trim())
              .catch(() => document.getElementById('version').textContent = 'Unable to fetch');
            
            fetch('/hostname')
              .then(r => r.text())
              .then(h => document.getElementById('hostname').textContent = h.trim())
              .catch(() => document.getElementById('hostname').textContent = 'Unable to fetch');
        </script>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.26.2
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 32Mi
        volumeMounts:
        - name: nginx-version-page
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
      volumes:
      - name: nginx-version-page
        configMap:
          name: nginx-version-page
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    cert-manager.io/cluster-issuer: ishiori-local-general-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - rollouts-nginx.kube.ishiori.lnet
    secretName: rollouts-nginx-tls
  rules:
  - host: rollouts-nginx.kube.ishiori.lnet
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
