apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-sidekiq
  namespace: sandbox
  labels:
    app: demo-app
    component: sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      component: sidekiq
  template:
    metadata:
      labels:
        app: demo-app
        component: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: demo-app:latest
        imagePullPolicy: IfNotPresent
        command: ["bundle"]
        args: ["exec", "sidekiq"]
        env:
        - name: RAILS_ENV
          value: "current"
        - name: RACK_ENV
          value: "current"
        - name: REDIS_SESSION_SENTINEL_HOST
          value: "host.orb.internal"
        - name: REDIS_SIDEKIQ_SENTINEL_HOST
          value: "host.orb.internal"
        - name: REDIS_MISC_SENTINEL_HOST
          value: "host.orb.internal"
        - name: KEYCLOAK_URL
          value: "http://host.orb.internal:8080"

