apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: sandbox
spec:
  template:
    spec:
      initContainers:
      - name: prepare-plugins-dir
        command:
          - /bin/bash
        args:
          - -ec
          - |
            #!/bin/bash
            
            echo "Copying plugins dir to empty dir"
            # In order to not break the possibility of installing custom plugins, we need
            # to make the plugins directory writable, so we need to copy it to an empty dir volume
            # Official RabbitMQ image has plugins at /opt/rabbitmq/plugins
            mkdir -p /emptydir/app-plugins-dir
            cp -r /opt/rabbitmq/plugins/* /emptydir/app-plugins-dir/

