apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: build-and-push-dockerfile
  namespace: workflows-sandbox
spec:
  entrypoint: build-and-push
  volumes:
  - name: dockerfile-volume
    configMap:
      name: dockerfile
  templates:
  - name: build-and-push
    container:
      image: moby/buildkit:latest
      command:
      - buildctl-daemonless.sh
      args:
      - build
      - --frontend=dockerfile.v0
      - --local=context=/workspace
      - --local=dockerfile=/workspace
      - --output=type=image,name=docker-registry.cluster-registry.svc.cluster.local:5000/hello-chloe:latest,push=true,registry.insecure=true
      volumeMounts:
      - name: dockerfile-volume
        mountPath: /workspace
        readOnly: true
      securityContext:
        privileged: true
