apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisinsight-pvc
  namespace: operations
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: operations
  labels:
    app: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: redisinsight
        image: redis/redisinsight:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5540
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: data
          mountPath: /db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redisinsight-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  namespace: operations
spec:
  type: NodePort
  selector:
    app: redisinsight
  ports:
  - name: http
    port: 32081
    targetPort: http
    nodePort: 32081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redisinsight
  namespace: operations
  annotations:
    cert-manager.io/cluster-issuer: ishiori-local-general-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - redisinsight.kube.ishiori.lnet
    secretName: redisinsight-tls
  rules:
  - host: redisinsight.kube.ishiori.lnet
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redisinsight
            port:
              number: 32081

