apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: sidekiq-sandbox
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: sidekiq-sandbox
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
      - name: setup
        image: redis:6.2.20-bookworm
        command:
        - /bin/bash
        - -c
        - |
          chmod +x /scripts/redis-cluster-provision.sh
          /scripts/redis-cluster-provision.sh
        env:
        - name: PERSISTENT_MOUNT_PATH
          value: "/data"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: REDIS_MASTER_HOST_NAME
          value: "redis-0"
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: data
          mountPath: /data
        securityContext:
          privileged: true
          runAsUser: 0
      containers:
      - name: redis
        image: redis:6.2.20-bookworm
        command:
        - /bin/bash
        - -c
        - |
          ulimit -n 16000
          redis-server /data/redis/redis.conf
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        securityContext:
          runAsUser: 0
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
      - name: scripts
        configMap:
          name: static-files
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
