---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-scripts
  namespace: sidekiq-sandbox
data:
  init.sh: |
    #!/bin/bash
    set -e
    
    # Get password from secret
    REDIS_PASSWORD=$(cat /etc/redis-password/password)
    
    # Always initialize redis.conf fresh from base
    cp /tmp/redis-base.conf /etc/redis/redis.conf
    
    # Add authentication
    echo "requirepass $REDIS_PASSWORD" >> /etc/redis/redis.conf
    echo "masterauth $REDIS_PASSWORD" >> /etc/redis/redis.conf
    
    # Determine if this is the master (first pod)
    if [[ "$HOSTNAME" != "redis-sentinel-0" ]]; then
      echo "replicaof redis-sentinel-0.redis-sentinel-headless.sidekiq-sandbox.svc.cluster.local 6379" >> /etc/redis/redis.conf
    fi
    
    # Create/update Sentinel configuration
    cat > /etc/redis/sentinel.conf <<EOF
    bind 0.0.0.0
    port 26379
    dir /etc/redis
    sentinel monitor mymaster 127.0.0.1 6379 2
    sentinel auth-pass mymaster $REDIS_PASSWORD
    sentinel down-after-milliseconds mymaster 5000
    sentinel parallel-syncs mymaster 1
    sentinel failover-timeout mymaster 10000
    EOF
    
    echo "Configuration initialized"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-headless
  namespace: sidekiq-sandbox
spec:
  clusterIP: None
  selector:
    app: redis-sentinel
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: sentinel
    port: 26379
    targetPort: 26379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: sidekiq-sandbox
spec:
  selector:
    app: redis-sentinel
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: sentinel
    port: 26379
    targetPort: 26379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: sidekiq-sandbox
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  serviceName: redis-sentinel-headless
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      initContainers:
      - name: init-redis
        image: localhost:30500/custom-redis:latest
        command:
        - /bin/bash
        - -c
        - /scripts/init.sh
        volumeMounts:
        - name: data
          mountPath: /etc/redis
        - name: scripts
          mountPath: /scripts
        - name: redis-password
          mountPath: /etc/redis-password
          readOnly: true
      containers:
      - name: redis
        image: localhost:30500/custom-redis:latest
        command:
        - redis-server
        - /etc/redis/redis.conf
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: data
          mountPath: /etc/redis
        - name: redis-password
          mountPath: /etc/redis-password
          readOnly: true
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - redis-cli -a $(cat /etc/redis-password/password) ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - redis-cli -a $(cat /etc/redis-password/password) ping
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: sentinel
        image: localhost:30500/custom-redis:latest
        command:
        - redis-sentinel
        - /etc/redis/sentinel.conf
        ports:
        - containerPort: 26379
          name: sentinel
        volumeMounts:
        - name: data
          mountPath: /etc/redis
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -p
            - "26379"
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -p
            - "26379"
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: scripts
        configMap:
          name: redis-scripts
          defaultMode: 0755
      - name: redis-password
        secret:
          secretName: redis-password
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
