---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: sidekiq-sandbox
spec:
  encryptedData:
    password: AgBWVqOr58V6C3H1YRJXwhfx5k4+XYjHKcd1y+rA6ib6laetXOSRS8E8yxjdkpyDbdgSDaIkVnZqRkKCAAP4vGWMbuHKb8m1ZxeLA7nXC5HFoYc5LHwkBBWMasTrugUIJFzsKyjgb4dZNPyJqacwlIVozWlsdLlMLINrrxp7DfrEI2Zewv/HOMquikUzqxQxZbz+Lhl+bL8PRAgyKUKJQmiaP90I1nen29OpibmZJm7ruNlmRV89ZWuvV4+s9ddcolVerN0lMb9ZQk9uPmTpqPTUetsJhkGFoIb1C9DrBSNiCWqvVoA0ksmPcCuofBseSIJZpJ6g1vxsViKC0IhXgntG3xQi2blqz2wpwpzhIzlxamChqLewY4JyaZa1AEOpYqVppuZHl79IwWV0lc/Ko1llb3RLzScCg8LPAvMLBNQAc1ns5HJQcg9WRQuGKS47r/LWtCeme+qd1/0kAelEOQkxE4R6XakrXB4uTuQEYXpMuSbdBHC/DcuMlw8ZYbgegazZqFb14mU3U2KmyGzqHs1yiyuE1LqgiGXJ/QmeEe1lkw+AkdU0BhvEvp6kktAO9MDBrYneGxWeZoberbT5h/+5RQ4dsJOEvMbb44P+McvBzxOZHeaCTo0hnH4rLAzF5xdPEMkEBWuVGzgcMSEd5rKITNhHY7VUrmUqJ+ykx0+05ndrNP4R/YaAc6XOGjFiPNRhDdxkKa2e/g==
  template:
    metadata:
      name: redis-password
      namespace: sidekiq-sandbox
