apiVersion: v1
kind: Pod
metadata:
  name: host-proxy
  namespace: shared-app
  labels:
    app: host-proxy
spec:
  hostNetwork: true
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command:
    - socat
    args:
    - TCP-LISTEN:63790,fork,reuseaddr
    - TCP:127.0.0.1:6379
    ports:
    - name: redis
      containerPort: 63790
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: port6379
  namespace: shared-app
spec:
  type: ClusterIP
  selector:
    app: host-proxy
  ports:
  - name: redis
    port: 6379
    targetPort: 63790
    protocol: TCP
