---
# PersistentVolumeClaim for PostgreSQL data persistence
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: shared-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# StatefulSet for PostgreSQL with persistent storage
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: shared-app
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:16-alpine
        ports:
        - name: postgres
          containerPort: 5432
          protocol: TCP
        env:
        # Database name
        - name: POSTGRES_DB
          value: "shared_db"
        # Self-documenting user: 'shared_user' with full privileges on 'shared_db'
        # This user can be used by applications in the cluster to connect to PostgreSQL
        - name: POSTGRES_USER
          value: "shared_user"
        # Password sourced from global-password SealedSecret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: global-password
              key: password
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U shared_user -d shared_db
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U shared_user -d shared_db
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
          # Subpath to avoid postgres complaining about lost+found directory
          subPath: postgres
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-pvc
---
# Service for PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: shared-app
  labels:
    app: postgresql
  annotations:
    dns.name: "postgresql.shared-app.svc.cluster.local"
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
